# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_dist <- function(x, power = 2L) {
    .Call('cstab_fast_dist', PACKAGE = 'cstab', x, power)
}

equal <- function(x) {
    .Call('cstab_equal', PACKAGE = 'cstab', x)
}

rootChoose <- function(n, k, root) {
    .Call('cstab_rootChoose', PACKAGE = 'cstab', n, k, root)
}

rootChooseLookup <- function(n, k, lookup) {
    .Call('cstab_rootChooseLookup', PACKAGE = 'cstab', n, k, lookup)
}

rootCombLookup <- function(ns, lookup) {
    .Call('cstab_rootCombLookup', PACKAGE = 'cstab', ns, lookup)
}

stabExp <- function(ns, lookup) {
    .Call('cstab_stabExp', PACKAGE = 'cstab', ns, lookup)
}

#' Create lookup table
#'
#' Create lookup table for faculties
#'
#' @param n integer specifying the number of
#' @param root numeric specifying the root used to avoid
#'   machine limit.
#'
#' @export
lookup <- function(n = 10000L, root = 200) {
    .Call('cstab_lookup', PACKAGE = 'cstab', n, root)
}

kmeans_predict <- function(kmeans, data) {
    .Call('cstab_kmeans_predict', PACKAGE = 'cstab', kmeans, data)
}

