# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rootChoose <- function(n, k, root) {
    .Call('cstab_rootChoose', PACKAGE = 'cstab', n, k, root)
}

rootChooseLookup <- function(n, k, lookup) {
    .Call('cstab_rootChooseLookup', PACKAGE = 'cstab', n, k, lookup)
}

lookup <- function(n, root) {
    .Call('cstab_lookup', PACKAGE = 'cstab', n, root)
}

rootCombLookup <- function(ns, lookup) {
    .Call('cstab_rootCombLookup', PACKAGE = 'cstab', ns, lookup)
}

stabExp <- function(ns, lookup) {
    .Call('cstab_stabExp', PACKAGE = 'cstab', ns, lookup)
}

